/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_jni_Hello */

#ifndef _Included_com_demo_jni_Hello
#define _Included_com_demo_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
#undef com_demo_jni_Hello_M0
#define com_demo_jni_Hello_M0 0L
#undef com_demo_jni_Hello_M1
#define com_demo_jni_Hello_M1 1L
#undef com_demo_jni_Hello_M2
#define com_demo_jni_Hello_M2 2L
#undef com_demo_jni_Hello_M3
#define com_demo_jni_Hello_M3 3L
/*
 * Class:     com_demo_jni_Hello
 * Method:    change
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_demo_jni_Hello_change
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
